# Runs on every commit after: pre-commit install
# Manual run: pre-commit run --all-files

repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        types: [python]
        exclude: ^migrations/

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        types: [python]
        exclude: ^migrations/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [--fix]
        types: [python]
        exclude: ^migrations/
